namespace Inventec.Desktop.Common.LibraryMessage
{
    public partial class Message
    {
        public enum Enum
        {
            HeThongTBKQXLYCCuaFrontendThanhCong,
            HeThongTBKQXLYCCuaFrontendThatBai,
            HeThongTBXuatHienExceptionChuaKiemDuocSoat,
            TaiKhoanKhongCoQuyenThucHienChucNang,
            NguoiDungChuaNhapTaiKhoanDeDangNhap,
            NguoiDungChuaNhapMatKhauDeDangNhap,
            NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac,
            TieuDeCuaSoThongBaoLaThongBao,
            TieuDeCuaSoThongBaoLaCanhBao,
            TieuDeCuaSoThongBaoLaLoi,
            PhanMemKhongKetNoiDuocToiMayChuHeThong,
            HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong,
            NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap,
            HeThongThongBaoMoTaChoWaitDialogForm,
            HeThongThongBaoTieuDeChoWaitDialogForm,
            HeThongThongBaoMoTaChoUpdatingDialogForm,
            NguoiDungNhapTuoiBenhNhanKhongHopLe,
            NguoiDungNhapThangSinhLonHonHienTai,
            NguoiDungNhapNgaySinhLonHonHienTai,
            NguoiDungNhapNamSinhKhongHopLe,
            NguoiDungNhapThangSinhKhongHopLe,
            NguoiDungNhapNgaySinhKhongHopLe,
            NguoiDungNhapThangBatDauCoHieuLucTheBHYTKhongHopLe,
            NguoiDungNhapNgayBatDauCoHieuLucTheBHYTKhongHopLe,
            NguoiDungNhapNamHetHieuLucTheBHYTKhongHopLe,
            NguoiDungNhapThangHetHieuLucTheBHYTKhongHopLe,
            NguoiDungNhapNgayHetHieuLucTheBHYTKhongHopLe,
            NguoiDungNhapInPhieuDangKyYeuCauDichVuKhamKhongCoDuLieuDangKyKham,
            NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe,
            NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe,
            HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong,
            HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong,
            HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong,
            HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong,
            HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong,
            HeThongTBCuaSoThongBaoBanCoMuonQuyetToanDuLieuKhong,
            NguoiDungNhapNamKhongHopLe,
            NguoiDungNhapThangKhongHopLe,
            NguoiDungNhapNgayKhongHopLe,
            NguoiDungNhapTruongHopBHYTKhongChiTraChiPhiVuiLongXemLaiCacDuLieuLienQuan,
            NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong,
            TieuDeThongTinHienThiPhanTrang,
            HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai,
            HeThongTBKetNoiDenMayChuTot,
            HeThongTBKetNoiDenMayChuKhongTot,
            HeThongTBKetNoiDenMayChuKhongOnDinh,
            HeThongTBKetNoiDenMayChuThatBai,
            HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong,
            HeThongTBTruongDuLieuBatBuocPhaiNhap,
            HeThongTBDuLieuNhapVaoKhongHopLe,
            NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHinh,
            ChucNangDangPhatTrienVuiLongThuLaiSau,
            ChiDinhThuoc_SoLuongXuatLonHonSpoLuongKhadungTrongKho,
            ChiDinhThuoc_KhongCoDoiTuongThanhToan,
            ChiDinhDichVu_KhongCoDoiTuongThanhToan,
            ChiDinhDichVuKham_ChuaCoYeuCauChiDinhDichVu,
            ChiDinhDichVuKham_ChuaChonPhongXuLy,
            HuyKetThucYeuCau_KhongDungNguoiTraKetQua,
            HuyKetThucYeuCau_HoSoDieuTriDaKetThuc,
            XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau,
            XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau,
            XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong,

            NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec,
            NguoiDungNhapDuLieuKhongHopLe,
            TruongDuLieuBatBuoc,
            HeThongTBBanQuyenKhongHopLe,
            ThieuTruongDuLieuBatBuoc,
            HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu,
            XuatTraThuoc_ChuaChonThuocVatTuDeTra,
            HeThongThongBaoThoiGianDenBeHonThoiGianTu,
            NguoiDungNhapNgayPhaiNhoHonNgayHienTai,
            DungLuongFileDinhKemQuaLon,

            ChamSoc_DuLieuChiTietKhongTheCungLoaiChamSoc,
            ExecuteRoom_DichVuDaCoDichVuDinhKemKhongChoPhepHuyBatDau,
            HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau,
            NguoiDungNhapSoLonThuocKeDuoiMucCanhBaoTonKho,

            NguoiDungNhapSoTheBHYTKhongHopLe,
            NguoiDungNhapHanTheTuPhaiNhoHonHanTheDen,

            ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua,

            NguoiDungNhapThongBaoBanCanChonPhongDeTaoYeuCauDichVu,
            CanhBaoTheBhytSapHatHan,
            HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe,
            ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull,
            ThongBaoDuLieuTrong,

            SuaChiDinhDichVu_KhongCoDoiTuongThanhToan,
            SuaChiDinhDichVu_KhongCoDoiSoLuong,
            TreEmCoGiayKaiSinhPhaiNhapDuThongTinHanhChinh,
            HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting,

        }
    }
}
